# Generated by Django 4.2.2 on 2023-06-15 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='asignatura',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Notas',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
