# Generated by Django 4.2.2 on 2023-06-15 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor_jefe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.profesor'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.curso'),
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Notas',
        ),
    ]
