# Generated by Django 4.2.2 on 2023-06-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_remove_notas_alumno_remove_notas_asignatura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'permissions': [('permiso_alumno', 'Puede acceder a las interfaces de alumno')]},
        ),
        migrations.AlterModelOptions(
            name='inspector',
            options={'permissions': [('permiso_inspector', 'Puede acceder a las interfaces de inspector')]},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'permissions': [('permiso_profesor', 'Puede acceder a las interfaces de profesor')]},
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='nombre',
        ),
    ]
