# Generated by Django 4.2.2 on 2023-06-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_alumno_options_alter_inspector_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='nombre',
        ),
    ]
