# Generated by Django 4.2.2 on 2023-06-15 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_remove_inspector_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='profesor_jefe',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Inspector',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
